@api=http://localhost:3000/bookings

### Obtener reservas 
GET {{api}}

### Obtener una única reserva
GET {{api}}/1

### Obtener cantidad de reservas
GET {{api}}/count

### eliminar reservas
DELETE {{api}}/11

### actualizar reservas
PUT {{api}}/10
Content-Type: application/json 
{
"name": "prueba de nodeJs"
}